---
#################################################
# Tasks to install additional repos
- name: RedHat | Install epel-elease
  yum: name=epel-release state=latest update_cache=yes

- name: RedHat | Install mysql-community-release
  yum: name=http://repo.mysql.com/mysql-community-release-el7-7.noarch.rpm state=present

- name: RedHat | get the indigo repository conf
  get_url: url={{ item.url }} dest={{ item.dest }}
  with_items:
    - { url: 'http://repo.indigo-datacloud.eu/repos/1/indigo1-testing.repo', dest: '/etc/yum.repos.d/indigo1-testing.repo' }

#################################################
# Tasks to install packages
- name: RedHat | Install necessary packages
  yum: name={{ item }} state=latest update_cache=yes
  with_items:
    - curl
    - libssh2
    - mpich
    - mpich-autoload
    - mysql-community-devel
    - mysql-community-server
    - MySQL-python
    - munge
    - munge-libs
    - openssl
    - sudo
    - wget
    - nfs-utils
    - git
    - gcc-c++
    - bzip2
    - make
    - netcdf-devel

- name: RedHat | 2nd set of packages slurm ophidia and libmatheval - the ones from the indigo repos
  yum: name={{ item }} state=latest update_cache=yes disable_gpg_check=yes
  with_items:
    - libmatheval
    - ophidia-analytics-framework
    - ophidia-primitives
    - slurm
    - slurm-munge
    - slurm-plugins

#################################################
# Tasks for folder creation and file move
- name: RedHat | Copy oph-primitives/lib to /usr/lib64/mysql/plugin
  shell: cp /usr/local/ophidia/oph-cluster/oph-primitives/lib/liboph_*.so /usr/lib64/mysql/plugin/
  args:
    executable: /bin/bash
    creates: /usr/lib64/mysql/plugin/liboph_*.so

- name: RedHat | Create user for Ophidia framwork
  user: name={{ oph_user }} shell=/bin/bash generate_ssh_key=yes ssh_key_bits=2048

- name: RedHat | ownership of Ophidia framework folders
  file: path=/usr/local/ophidia/oph-cluster/oph-analytics-framework owner={{ oph_user }} group={{ oph_user }} recurse=yes

- name: RedHat | Creates NFS shared directory
  file: path=/data state=directory owner=root group=root

- name: RedHat | sudo does not require tty
  lineinfile:
    dest=/etc/sudoers
    state=present
    regexp=^requiretty
    line='Defaults    !requiretty'

- name: RedHat | ownership of /etc/munge
  file: path=/etc/munge owner=munge group=root

#######################################################
# Tasks to setup/config mysql and necessary databases
- name: RedHat | ownership mysql for /var/log/mysqld.log
  file: path=/var/log/mysqld.log owner=mysql group=root

#######################################################
# Tasks to set data in NFS shared folder
- name: RedHat | Delete web folder
  file: path=/var/www/html/ophidia state=absent

#######################################################
# Tasks to set permissions
- name: RedHat | Set permissions on Ophidia folders
  file: path=/usr/local/ophidia owner={{ oph_user }} group={{ oph_user }} state=directory recurse=yes

- name: RedHat | Set permissions on Ophidia web space
  file: path=/data/ophidia owner={{ oph_user }} group={{ oph_user }} state=directory recurse=yes

- include: io_python.yml
