---
# Common installation tasks
- include: common_packages.yml

#################################################
# Tasks to install specific packages
- name: RedHat | 2nd set of packages
  yum: name={{ item }} state=latest
  with_items:
    - httpd
    - php
    - gsoap
    - java-1.7.0-openjdk

- name: RedHat | 2nd set of packages ophidia and libmatheval - the ones from the indigo repos
  yum: name={{ item }} state=latest update_cache=yes disable_gpg_check=yes
  with_items:
    - libmatheval
    - ophidia-server
    - ophidia-analytics-framework
    - ophidia-primitives
    - ophidia-terminal

#################################################
# Tasks for user and folder creation
- name: RedHat | Copy oph-primitives/lib to /usr/lib64/mysql/plugin
  shell: /bin/cp -rf /usr/local/ophidia/oph-cluster/oph-primitives/lib/liboph_*.so /usr/lib64/mysql/plugin/

- name: RedHat | Create user for Ophidia server
  user: name={{ oph_user }} shell=/bin/bash generate_ssh_key=yes ssh_key_bits=2048

- name: RedHat | Creates Ophidia extra directory
  file: path=/usr/local/ophidia/extra state=directory owner={{ oph_user }} group={{ oph_user }}

- name: RedHat | Creates NFS shared directory
  file: path=/data state=directory owner=root group=root

- name: RedHat | sudo does not require tty
  lineinfile:
    dest=/etc/sudoers
    state=present
    regexp=^requiretty
    line='Defaults    !requiretty'

#######################################################
# Tasks to setup/config mysql and necessary databases
- name: RedHat | ownership mysql for /var/log/mysqld.log
  file: path=/var/log/mysqld.log owner=mysql group=root

#######################################################
# Tasks to set permissions
- name: RedHat | Set permissions on Ophidia folders
  file: path=/usr/local/ophidia owner={{ oph_user }} group={{ oph_user }} state=directory recurse=yes

#- include: server_tomcat.yml
