#################################################
# Tasks for general configuration
- name: RedHat | Copy template of ophidia server server.conf
  template:
    src=server.conf.j2
    dest=/usr/local/ophidia/oph-server/etc/server.conf
    mode=0644
    owner={{ oph_user }}
    group={{ oph_user }}

- name: RedHat | Copy template of ophidia server ophidiadb.conf
  template:
    src=ophidiadb.conf.j2
    dest=/usr/local/ophidia/oph-server/etc/ophidiadb.conf
    mode=0644
    owner={{ oph_user }}
    group={{ oph_user }}

#######################################################
# Tasks to set data in NFS shared folder
- name: RedHat | Create folder for sessions
  file: path=/data/ophidia owner={{ oph_user }} group={{ oph_user }} state=directory

- name: RedHat | Create folder for data
  file: path=/data/repository owner={{ oph_user }} group={{ oph_user }} state=directory

- name: RedHat | Copy file from web folder
  copy: src=/var/www/html/ophidia dest=/data

- name: RedHat | Delete web folder
  file: path=/var/www/html/ophidia state=absent

- name: RedHat | Create symlink on Ophidia web space
  file: src=/data/ophidia dest=/var/www/html/ophidia state=link

#################################################
# Tasks for Ophidia server SSL certs
- name: RedHat | Check root SSL cert
  stat: path=/usr/local/ophidia/oph-server/etc/cert/cacert.pem
  register: cacert

- name: RedHat | Check server SSL cert
  stat: path=/usr/local/ophidia/oph-server/etc/cert/myserver.pem
  register: myserver

- name: RedHat | Creating root SSL cert
  command: >
    openssl req
      -newkey rsa:1024
      -passout pass:{{ cert_passwd }}
      -subj "/"
      -sha1
      -keyout rootkey.pem
      -out rootreq.pem
  args:
    chdir: /usr/local/ophidia/oph-server/etc/cert
    creates: /usr/local/ophidia/oph-server/etc/cert/rootreq.pem
  become: yes
  become_user: "{{ oph_user }}"
  when: cacert.stat.exists == False or myserver.stat.exists == False

- name: RedHat | Sign root SSL cert
  command: >
    openssl x509
      -req
      -in rootreq.pem
      -passin pass:{{ cert_passwd }}
      -sha1
      -extensions v3_ca
      -signkey rootkey.pem
      -out rootcert.pem
  args:
    chdir: /usr/local/ophidia/oph-server/etc/cert
    creates: /usr/local/ophidia/oph-server/etc/cert/rootcert.pem
  become: yes
  become_user: "{{ oph_user }}"
  when: cacert.stat.exists == False or myserver.stat.exists == False

- name: RedHat | merge cert and key of root cert
  shell: cat rootcert.pem rootkey.pem > cacert.pem
  args:
    chdir: /usr/local/ophidia/oph-server/etc/cert
    executable: /bin/bash
  become: yes
  become_user: "{{ oph_user }}"
  when: cacert.stat.exists == False or myserver.stat.exists == False

- name: RedHat | Creating server SSL cert
  command: >
    openssl req
      -newkey rsa:1024
      -passout pass:{{ cert_passwd }}
      -subj "/"
      -sha1
      -keyout serverkey.pem
      -out serverreq.pem
  args:
    chdir: /usr/local/ophidia/oph-server/etc/cert
    creates: /usr/local/ophidia/oph-server/etc/cert/serverreq.pem
  become: yes
  become_user: "{{ oph_user }}"
  when: cacert.stat.exists == False or myserver.stat.exists == False

- name: RedHat | Sign server SSL cert
  command: >
    openssl x509
      -req
      -in serverreq.pem
      -passin pass:{{ cert_passwd }}
      -sha1
      -extensions usr_cert
      -CA cacert.pem
      -CAkey cacert.pem
      -CAcreateserial
      -out servercert.pem
  args:
    chdir: /usr/local/ophidia/oph-server/etc/cert
    creates: /usr/local/ophidia/oph-server/etc/cert/servercert.pem
  become: yes
  become_user: "{{ oph_user }}"
  when: cacert.stat.exists == False or myserver.stat.exists == False

- name: RedHat | merge cert and key of server cert
  shell: cat servercert.pem serverkey.pem rootcert.pem > myserver.pem
  args:
    chdir: /usr/local/ophidia/oph-server/etc/cert
    executable: /bin/bash
  become: yes
  become_user: "{{ oph_user }}"
  when: cacert.stat.exists == False or myserver.stat.exists == False

- name: RedHat | Remove intermediate certs
  file: path={{ item }} state=absent
  with_items:
    - /usr/local/ophidia/oph-server/etc/cert/rootcert.pem
    - /usr/local/ophidia/oph-server/etc/cert/rootkey.pem
    - /usr/local/ophidia/oph-server/etc/cert/rootreq.pem
    - /usr/local/ophidia/oph-server/etc/cert/servercert.pem
    - /usr/local/ophidia/oph-server/etc/cert/serverkey.pem
    - /usr/local/ophidia/oph-server/etc/cert/serverreq.pem
    - /usr/local/ophidia/oph-server/etc/cert/cacert.srl

#######################################################
# Tasks to setup/config mysql and necessary databases
- name: RedHat | mysql prepare system tables
  command: /usr/bin/mysql-systemd-start pre
  become: true
  become_user: mysql

- name: RedHat | Start mysql_safe
  shell: pgrep mysqld_safe || (/usr/bin/mysqld_safe --user=mysql 2>&1 > /dev/null &)
  args:
    executable: /bin/bash

- name: RedHat | Wait for mysql start
  wait_for: path=/var/lib/mysql/mysql.sock

- name: RedHat | Set mysql root passwd
  mysql_user: name=root password={{ ophdb_passwd }}

- name: RedHat | Copy template of .my.cnf to oph_user
  template:
    src=.my.cnf.j2
    dest=/home/{{ oph_user }}/.my.cnf
    mode=0600
    owner={{ oph_user }}
    group={{ oph_user }}

- name: RedHat | Copy template of .my.cnf to root
  template:
    src=.my.cnf.j2
    dest=/root/.my.cnf
    mode=0600
    owner=root
    group=root

- name: RedHat | Remove hostname user
  mysql_user: name='root' host='{{ ansible_hostname }}' state=absent

- name: RedHat | import primitives
  mysql_db: name=mysql state=import target=/usr/local/ophidia/oph-cluster/oph-primitives/etc/create_func.sql

- name: RedHat | create ophidia databases
  mysql_db: name={{ item }} state=present
  with_items:
    - ophidiadb
    - oph_dimensions

- name: RedHat | import ophidia analytics db
  mysql_db: name=ophidiadb state=import target=/usr/local/ophidia/oph-cluster/oph-analytics-framework/etc/ophidiadb.sql

- name: RedHat | Copy template of ophdb-partition.sql to root
  template:
    src=ophdb-partition.sql.j2
    dest=/tmp/ophdb-partition.sql
    mode=0600
    owner=root
    group=root

- name: RedHat | import ophdb-partition.sql
  mysql_db: name=ophidiadb state=import target=/tmp/ophdb-partition.sql

- name: RedHat | Grant Mysql privileges
  mysql_user: name=root password='{{ ophdb_passwd }}' host='{{ mysql_subnet }}' priv={{ item }}
  with_items:
    - ophidiadb.*:ALL
    - oph_dimensions.*:ALL
    - mysql.*:EXECUTE

#######################################################
# Tasks to generate DSA keys for oph_user
- name: RedHat | key generation
  shell: ssh-keygen -t dsa -f /home/{{ oph_user }}/.ssh/id_dsa -N "" -q
  args:
    executable: /bin/bash
    creates: /home/{{ oph_user }}/.ssh/id_dsa
  become: yes
  become_user: "{{ oph_user }}"

- name: RedHat | Copy the key to authorized_keys file
  shell:  (grep -f id_dsa.pub authorized_keys ) || (cat id_dsa.pub >> authorized_keys)
  args:
    chdir: /home/{{ oph_user }}/.ssh
    executable: /bin/bash
  become: yes
  become_user: "{{ oph_user }}"

- name: RedHat | Set permissions on authorized_keys
  file: path=/home/{{ oph_user }}/.ssh/authorized_keys mode=600 owner={{ oph_user }} group={{ oph_user }}
  become: yes
  become_user: "{{ oph_user }}"

- name: RedHat | Remove nologin
  file: path=/run/nologin state=absent

#######################################################
# Tasks to start the services
- name: RedHat | start httpd
  shell: pgrep httpd || /usr/sbin/httpd

- name: RedHat | start sshd
  shell: pgrep sshd || /usr/sbin/sshd

- name: RedHat | Run Tomcat
  shell:
    (ps aux | grep /usr/local/ophidia/extra/apache-tomcat-7.0.72 | grep -v grep)  || nohup /usr/local/ophidia/extra/apache-tomcat-7.0.72/bin/startup.sh
  args:
    executable: /bin/bash
  become: yes
  become_user: "{{ oph_user }}"

#######################################################
# Task to start Ophidia service
- name: RedHat | Start ophidia server
  shell: pgrep oph_server || (oph_server 2>&1 > /dev/null &)
  args:
    executable: /bin/bash
  become: yes
  become_user: "{{ oph_user }}"

