
#################################################
# Tasks to install Tomcat and Thredds
- name: RedHat | Download Tomcat
  get_url:
    url: "http://it.apache.contactlab.it/tomcat/tomcat-7/v7.0.72/bin/apache-tomcat-7.0.72.tar.gz"
    dest: /usr/local/ophidia/extra/apache-tomcat-7.0.72.tar.gz
    force: no
    force_basic_auth: yes
    timeout: 1000
  become: yes
  become_user: "{{ oph_user }}"

- name: RedHat | Extract Tomcat
  command: tar -xzf apache-tomcat-7.0.72.tar.gz 
  args:
    chdir: /usr/local/ophidia/extra 
    creates: /usr/local/ophidia/extra/apache-tomcat-7.0.72
  become: yes
  become_user: "{{ oph_user }}"

- name: RedHat | Configure Tomcat
  template:
    src=server.xml.j2
    dest=/usr/local/ophidia/extra/apache-tomcat-7.0.72/conf/server.xml
    mode=0644
    owner={{ oph_user }}
    group={{ oph_user }}

- name: RedHat | Configure Tomcat
  template:
    src=setenv.sh.j2
    dest=/usr/local/ophidia/extra/apache-tomcat-7.0.72/bin/setenv.sh
    mode=0644
    owner={{ oph_user }}
    group={{ oph_user }}

- name: RedHat | Run Tomcat
  shell: 
    (ps aux | grep /usr/local/ophidia/extra/apache-tomcat-7.0.72 | grep -v grep) || nohup /usr/local/ophidia/extra/apache-tomcat-7.0.72/bin/startup.sh
  args:
    executable: /bin/bash
  become: yes
  become_user: "{{ oph_user }}"

- name: RedHat | Download Thredds
  get_url:
    url: "http://artifacts.unidata.ucar.edu/content/repositories/unidata-releases/edu/ucar/tds/4.6.6/tds-4.6.6.war"
    dest: /usr/local/ophidia/extra/tds-4.6.6.war
    force: no
    force_basic_auth: yes
    timeout: 1000
  become: yes
  become_user: "{{ oph_user }}"

- name: RedHat | Deploy Thredds
  copy: 
    src=/usr/local/ophidia/extra/tds-4.6.6.war
    dest=/usr/local/ophidia/extra/apache-tomcat-7.0.72/webapps/thredds.war
    owner="{{ oph_user }}"
    group="{{ oph_user }}"
    remote_src=no

- name: RedHat | Create base folder
  file: path={{ base_path }} owner={{ oph_user }} group={{ oph_user }} state=directory recurse=yes

- name: RedHat | Wait for Thredds deploy
  wait_for: path=/usr/local/ophidia/extra/apache-tomcat-7.0.72/content/thredds/catalog.xml

- name: RedHat | Configure Thredds
  template:
    src=catalog.xml.j2
    dest=/usr/local/ophidia/extra/apache-tomcat-7.0.72/content/thredds/catalog.xml
    mode=0644
    owner={{ oph_user }}
    group={{ oph_user }}

- name: RedHat | Wait for Thredds deploy
  wait_for: path=/usr/local/ophidia/extra/apache-tomcat-7.0.72/content/thredds/threddsConfig.xml

- name: RedHat | Configure Thredds
  template:
    src=threddsConfig.xml.j2
    dest=/usr/local/ophidia/extra/apache-tomcat-7.0.72/content/thredds/threddsConfig.xml
    mode=0644
    owner={{ oph_user }}
    group={{ oph_user }}

- name: RedHat | Stop Tomcat
  shell: (ps aux | grep /usr/local/ophidia/extra/apache-tomcat-7.0.72 | grep -v grep) && /usr/local/ophidia/extra/apache-tomcat-7.0.72/bin/shutdown.sh
  args:
    executable: /bin/bash
  become: yes
  become_user: "{{ oph_user }}"
