#######################################################
# Tasks to configure the workflows
- name: RedHat | Download the workflows
  git: repo=https://github.com/OphidiaBigData/ophidia-workflow-catalogue.git dest=/home/{{ oph_user }}/ophidia-workflow-catalogue
  become: yes
  become_user: "{{ oph_user }}"

- name: RedHat | Copy template of ophidia script oph_script_configuration
  template:
    src=oph_script_configuration.j2
    dest=/usr/local/ophidia/oph-cluster/oph-analytics-framework/etc/oph_script_configuration
    mode=0644
    owner={{ oph_user }}
    group={{ oph_user }}

#######################################################
# Tasks to install UV-CDAT
- name: RedHat | Create extra folder for Python
  file: path=/usr/local/ophidia/extra/src state=directory mode=0755 owner={{ oph_user }} group={{ oph_user }}
  become: yes
  become_user: "{{ oph_user }}"

- name: RedHat | Download Python
  get_url:
    url: https://www.python.org/ftp/python/3.5.0/Python-3.5.0.tgz
    dest: /usr/local/ophidia/extra/src
    force_basic_auth: yes
  become: yes
  become_user: "{{ oph_user }}"

- name: RedHat | Extract Python
  unarchive: src=/usr/local/ophidia/extra/src/Python-3.5.0.tgz dest=/usr/local/ophidia/extra/src
  become: yes
  become_user: "{{ oph_user }}"

- name: RedHat | Install Python
  shell:
    cd /usr/local/ophidia/extra/src/Python-3.5.0 && ./configure --prefix=/usr/local/ophidia/extra > /dev/null 2>&1 && make > /dev/null 2>&1 && make altinstall > /dev/null 2>&1
  args:
    executable: /bin/bash
  become: yes
  become_user: "{{ oph_user }}"

- name: RedHat | Download Anaconda
  get_url:
    url: http://repo.continuum.io/archive/Anaconda3-4.0.0-Linux-x86_64.sh
    dest: /usr/local/ophidia/extra/src
    force_basic_auth: yes
  become: yes
  become_user: "{{ oph_user }}"

- name: RedHat | Make executable the Anaconda script
  file: path=/usr/local/ophidia/extra/src/Anaconda3-4.0.0-Linux-x86_64.sh mode=0755 owner={{ oph_user }} group={{ oph_user }}
  become: yes
  become_user: "{{ oph_user }}"

- name: RedHat | Install Anaconda
  shell:
    ./Anaconda3-4.0.0-Linux-x86_64.sh -b -p /usr/local/ophidia/extra/anaconda3 > /dev/null 2>&1
  args:
    executable: /bin/bash
    chdir: /usr/local/ophidia/extra/src
  become: yes
  become_user: "{{ oph_user }}"
  environment:
    PATH: "/usr/local/ophidia/extra/bin:{{ ansible_env.PATH }}"

- name: RedHat | Create ophidia-nox
  shell:
    conda create -y -n ophidia-nox -c uvcdat/label/nightly -c uvcdat uvcdat-nox
  args:
    executable: /bin/bash
  become: yes
  become_user: "{{ oph_user }}"
  environment:
    PATH: "/usr/local/ophidia/extra/anaconda3/bin:{{ ansible_env.PATH }}"

- name: RedHat | Update PATH
  lineinfile:
    dest=/home/{{ oph_user }}/.bashrc
    regexp=''
    insertafter=EOF
    line='export PATH=/usr/local/ophidia/extra/anaconda3/bin:/usr/local/ophidia/extra/bin:$PATH'
  become: yes
  become_user: "{{ oph_user }}"

#################################################
# Tasks to install CDO
- name: RedHat | Download CDO
  get_url:
    url: "https://code.zmaw.de/attachments/download/13175/cdo-current.tar.gz"
    dest: /usr/local/ophidia/extra/src
    force_basic_auth: yes
    timeout: 1000
  become: yes
  become_user: "{{ oph_user }}"

- name: RedHat | Extract CDO
  unarchive: src=/usr/local/ophidia/extra/src/cdo-current.tar.gz dest=/usr/local/ophidia/extra/src
  become: yes
  become_user: "{{ oph_user }}"

- name: RedHat | Install CDO
  shell:
    cd /usr/local/ophidia/extra/src/cdo-1.8.0rc4 && ./configure --with-netcdf=yes > /dev/null 2>&1 && make > /dev/null 2>&1
  args:
    executable: /bin/bash
  become: yes
  become_user: "{{ oph_user }}"

- name: RedHat | Install CDO
  shell:
    cd /usr/local/ophidia/extra/src/cdo-1.8.0rc4 && make install > /dev/null 2>&1
  args:
    executable: /bin/bash

