---
#################################################
# Tasks to install additional repos
- name: RedHat | Install epel-elease
  yum: name=epel-release state=latest update_cache=yes

- name: RedHat | Install mysql-community-release
  yum: name=http://repo.mysql.com/mysql-community-release-el7-7.noarch.rpm state=present

- name: RedHat | get the indigo repository conf
  get_url: url={{ item.url }} dest={{ item.dest }}
  with_items:
    - { url: 'http://repo.indigo-datacloud.eu/repos/1/indigo1-testing.repo', dest: '/etc/yum.repos.d/indigo1-testing.repo' }

#################################################
# Tasks to install packages
- name: RedHat | Install necessary packages
  yum: name={{ item }} state=latest update_cache=yes
  with_items:
    - curl
    - gsoap
    - httpd
    - libssh2
    - mpich
    - mpich-autoload
    - mysql-community-devel
    - mysql-community-server
    - MySQL-python
    - munge
    - munge-libs
    - openssl
    - php
    - sudo
    - wget
    - nfs-utils
    - java-1.7.0-openjdk

- name: RedHat | 2nd set of packages slurm ophidia and libmatheval - the ones from the indigo repos
  yum: name={{ item }} state=latest update_cache=yes disable_gpg_check=yes
  with_items:
    - libmatheval
    - ophidia-server
    - ophidia-analytics-framework
    - slurm
    - slurm-munge
    - slurm-plugins

#################################################
# Tasks for user and folder creation
- name: RedHat | Create user for Ophidia server
  user: name={{ oph_user }} shell=/bin/bash generate_ssh_key=yes ssh_key_bits=2048

- name: RedHat | Creates Ophidia extra directory
  file: path=/usr/local/ophidia/extra state=directory owner={{ oph_user }} group={{ oph_user }}

- name: RedHat | Creates NFS shared directory
  file: path=/data state=directory owner=root group=root

- name: RedHat | sudo does not require tty
  lineinfile:
    dest=/etc/sudoers
    state=present
    regexp=^requiretty
    line='Defaults    !requiretty'

- name: RedHat | Creates slurmd spool directory
  file: path=/var/spool/slurmd state=directory owner=root group=root

- name: RedHat | ownership of /etc/munge
  file: path=/etc/munge owner=munge group=root

#######################################################
# Tasks to setup/config mysql and necessary databases
- name: RedHat | ownership mysql for /var/log/mysqld.log
  file: path=/var/log/mysqld.log owner=mysql group=root

#######################################################
# Tasks to set data in NFS shared folder
- name: RedHat | Create folder for sessions
  file: path=/data/ophidia owner={{ oph_user }} group={{ oph_user }} state=directory

- name: RedHat | Create folder for data
  file: path=/data/repository owner={{ oph_user }} group={{ oph_user }} state=directory

- name: RedHat | Copy file from web folder
  copy: src=/var/www/html/ophidia dest=/data

- name: RedHat | Delete web folder
  file: path=/var/www/html/ophidia state=absent

- name: RedHat | Create symlink on Ophidia web space
  file: src=/data/ophidia dest=/var/www/html/ophidia state=link

#######################################################
# Tasks to set permissions
- name: RedHat | Set permissions on Ophidia folders
  file: path=/usr/local/ophidia owner={{ oph_user }} group={{ oph_user }} state=directory recurse=yes

- name: RedHat | Set permissions on Ophidia web space
  file: path=/data/ophidia owner={{ oph_user }} group={{ oph_user }} state=directory recurse=yes

- include: tomcat.yml

- include: configuration.yml

